# Generated by Django 5.1.7 on 2025-03-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_walletfunding'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletfunding',
            name='reference',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='walletfunding',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=20, null=True),
        ),
    ]
