# Generated by Django 5.1.7 on 2025-03-24 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0005_transfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='bank_code',
            field=models.CharField(max_length=15),
        ),
    ]
