# Generated by Django 5.1.7 on 2025-03-24 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_alter_transfer_bank_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transfer',
            old_name='account_Name',
            new_name='account_name',
        ),
    ]
