# Generated by Django 5.1.7 on 2025-03-24 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0007_rename_account_name_transfer_account_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='amount',
            field=models.PositiveIntegerField(),
        ),
    ]
